### PR TITLE
Reza_framework_for_Contoller_Section (TSC)

### PR DESCRIPTION
**Pull request by reza-github**

### CODE REVIEW

**Review by jariarkko — COMMENTED** [review]
This email concerns Pull-request #8: Reza’s proposed text addition to
the controller section. This review is again a personal review, not
holding any hats, just providing my opinion.

This is overall good text and relatively ready for inclusion. There
are some places where one can cut a bit unnecessary text, and a few
sentences where a more matter-of-fact style would work better in an
IETF document. I also think we need to be careful in not making the
controller section too long. It may be useful to add some specific
discussions elsewhere under the considerations section of the
framework document. And some discussions may not  be needed
in this document, in my opinion, such as the part about closed loop
optimizations - that's an important topic but we don't need to talk about
it to explain the framework. And I don't think we want to get to the
discussion of e2e slices. Transport slices are components of those,
but we can leave  it at that.

By the way, I really liked the way that the section explained not just
the initial mapping but the mapping of telemetry etc. Good work!

I also wondered how well the controller and mapping sections
complement each other; the editors should probably do a pass to ensure
that each section has the right content. Eric, John: feel free to move
text around if it fits better the other section!

I left a few TODOs in the text that I'd propose we use. There were
a couple of unclear points, mostly related to concepts not introduced
earlier and/or whose need to be included was unclear to me.

I'd use this text, edited from Reza's original:

# Transport Slice Controller (TSC)

    The transport slice controller takes abstract requests for
    transport slices and implements them using a suitable underlying
    technology.  A transport slice controller is the key building
    block for control and management of the transport slice.  It
    provides the creation/modification/deletion, monitoring and
    optimization of transport Slices in a multi-domain, a
    multi-technology and multi-vendor environment.

    The controller provides the following functions:

    * Provides a technology-agnostic NBI for creation/modification/
      deletion of the transport slices.  The attributes of this
      interface will be discussed in section sssss.  In summary, the
      API exposed by this NBI communicates the endpoints of the
      transport slice, transport slice SLO, various policies, and
      provides a way to monitor the slice.
   
    * Using the network abstract topology, it provides mechanism to find
      the Service endpoints (these are technology specific).
      (TODO: this seems unclear. What endpoints are these, are why
      are they different from endpoints discussed earlier?)
   
    * Provides "Mapping Functions" for realization of transport slices.
      In other words, it will use the mapping functions which map
      technology-agnostic NBI request to technology-specific SBIs.
   
    * On its southbound interface, the controller monitors Telemetry
      data (e.g.  OAM results, Statistics, States etc.) for all
      technology-specific services/paths/tunnels which are used to
      realize the transport slice.
   
    * Aggregates all the Telemetry data of underlying realization of a
      transport slice (i.e. services/paths/tunnels) and calculate the
      current "Transport Slice SLO" and exposes them to "Higher level
      system" through its NBI.  It also raises a notification in case
      the transport slice is out of SLO.
   
    * Provides the abstract network topology and in specific the "inter-
      domain" links between multiple network domains.
      (TODO: This is unclear, at least to me.)

**Comment by Eric-Gray-Ericsson** [comment]
I propose modifying Jari's text to read:

Transport Slice Controller (TSC)

The transport slice controller takes abstract requests for
transport slices and implements them using a suitable underlying
technology.  A transport slice controller is the key building
block for control and management of the transport slice.  It
provides the creation/modification/deletion, monitoring and
optimization of transport Slices in a multi-domain, a
multi-technology and multi-vendor environment.

In discussion in this document, a southbound interface (SBI)
is used as a logical construct (that may or may not exist in 
practice) representing mechanisms used by the TSC in 
communicating with the underlying (abstract) network.

A TSC northbound interface is needed for communicating 
details of a transport slice, as well as providing information 
to a slice requester/consumer about transport slice status 
and performance.  The details for this NBI are not in scope
for this document.

The controller provides the following functions:

* Provides a technology-agnostic NBI for creation/modification/
  deletion of the transport slices.  The API exposed by this NBI 
  communicates the endpoints of the transport slice, transport 
  slice SLO parameters (and possibly monitoring thresholds), 
  applicable input selection (filtering) and various policies, and 
  provides a way to monitor the slice.

* Determines an abstract topology connecting the endpoints of
   the transport slice that meets criteria specified via the NBI.

* Provides "Mapping Functions" for realization of transport slices.
  In other words, it will use the mapping functions which: 
** map technology-agnostic NBI request to technology-specific SBIs.
** map filtering/selection information as necessary to entities in the 
    underlay network.

* Via an SBI, the controller monitors Telemetry data (e.g.  OAM results, 
   Statistics, States etc.) for all elements in the abstract topology used 
   to realize the transport slice.

* Aggregates Telemetry data from the underlying realization of a
  transport slice (i.e. services/paths/tunnels), calculates the
  current performance against transport slice SLO parameters and 
  exposes them to the transport slice consumer via the NBI.  The 
  TSC NBI may also include a capability to provide notification in 
  case the transport slice performance reaches threshold values
  defined by the transport slice consumer.

**Comment by Eric-Gray-Ericsson** [comment]
Minor changes to the bullets proposed, based on subsequent discussion:
* add to the second bullet, the following sentence: "The TSC also retains 
  information about the mapping of this abstract topology to underlying 
  components of the transport slice as necessary to monitor transport 
  slice status and performance."
* in the third bullet, replace "realization" with "the realization."
* in the next to last bullet, replace "monitors" with "collects."
* in the last bullet, replace "Aggregates" with "Using the" and replace "calculates" with "evaluates."

**Comment by Eric-Gray-Ericsson** [comment]
The modified text for adding is:

Transport Slice Controller (TSC)

The transport slice controller takes abstract requests for
transport slices and implements them using a suitable underlying
technology. A transport slice controller is the key building
block for control and management of the transport slice. It
provides the creation/modification/deletion, monitoring and
optimization of transport Slices in a multi-domain, a
multi-technology and multi-vendor environment.

In discussion in this document, a southbound interface (SBI)
is used as a logical construct (that may or may not exist in
practice) representing mechanisms used by the TSC in
communicating with the underlying (abstract) network.

A TSC northbound interface is needed for communicating
details of a transport slice, as well as providing information
to a slice requester/consumer about transport slice status
and performance. The details for this NBI are not in scope
for this document.

The controller provides the following functions:

* Provides a technology-agnostic NBI for creation/modification/
deletion of the transport slices. The API exposed by this NBI
communicates the endpoints of the transport slice, transport
slice SLO parameters (and possibly monitoring thresholds),
applicable input selection (filtering) and various policies, and
provides a way to monitor the slice.

* Determines an abstract topology connecting the endpoints of
the transport slice that meets criteria specified via the NBI.The 
TSC also retains information about the mapping of this abstract 
topology to underlying components of the transport slice as 
necessary to monitor transport slice status and performance.

* Provides "Mapping Functions" for the realization of transport slices.
  In other words, it will use the mapping functions which:
  - map technology-agnostic NBI request to technology-specific SBIs.
  - map filtering/selection information as necessary to entities in the
   underlay network.

* Via an SBI, the controller collects Telemetry data (e.g. OAM results,
   Statistics, States etc.) for all elements in the abstract topology used
   to realize the transport slice.

* Using the Telemetry data from the underlying realization of a
  transport slice (i.e. services/paths/tunnels), evaluates the
  current performance against transport slice SLO parameters and
  exposes them to the transport slice consumer via the NBI. The
  TSC NBI may also include a capability to provide notification in
  case the transport slice performance reaches threshold values
  defined by the transport slice consumer.

**Comment by sergiobelotti** [comment]
> The modified text for adding is:
> 
> Transport Slice Controller (TSC)
> 
> The transport slice controller takes abstract requests for
> transport slices and implements them using a suitable underlying
> technology. A transport slice controller is the key building
> block for control and management of the transport slice. It
> provides the creation/modification/deletion, monitoring and
> optimization of transport Slices in a multi-domain, a
> multi-technology and multi-vendor environment.
> 
> In discussion in this document, a southbound interface (SBI)
> is used as a logical construct (that may or may not exist in
> practice) representing mechanisms used by the TSC in
> communicating with the underlying (abstract) network.
> 
> A TSC northbound interface is needed for communicating
> details of a transport slice, as well as providing information
> to a slice requester/consumer about transport slice status
> and performance. The details for this NBI are not in scope
> for this document.
> 
> The controller provides the following functions:
> 
> * Provides a technology-agnostic NBI for creation/modification/
>   deletion of the transport slices. The API exposed by this NBI
>   communicates the endpoints of the transport slice, transport
>   slice SLO parameters (and possibly monitoring thresholds),
>   applicable input selection (filtering) and various policies, and
>   provides a way to monitor the slice.
> * Determines an abstract topology connecting the endpoints of
>   the transport slice that meets criteria specified via the NBI.The
>   TSC also retains information about the mapping of this abstract
>   topology to underlying components of the transport slice as
>   necessary to monitor transport slice status and performance.
> * Provides "Mapping Functions" for the realization of transport slices.
>   In other words, it will use the mapping functions which:
>   
>   * map technology-agnostic NBI request to technology-specific SBIs.
>   * map filtering/selection information as necessary to entities in the
>     underlay network.
> * Via an SBI, the controller collects Telemetry data (e.g. OAM results,
>   Statistics, States etc.) for all elements in the abstract topology used
>   to realize the transport slice.
> * Using the Telemetry data from the underlying realization of a
>   transport slice (i.e. services/paths/tunnels), evaluates the
>   current performance against transport slice SLO parameters and
>   exposes them to the transport slice consumer via the NBI. The
>   TSC NBI may also include a capability to provide notification in
>   case the transport slice performance reaches threshold values
>   defined by the transport slice consumer.

Looking at the text related to SBI it is not clear to me what does mean with logical construct , and it is not clear why this interface should not exist at all. Reading definition draft, it was clearly exposed the scope of Network Controller , that is practically in charge to select underlying resources to be used by TSC to create transport slice. I would expect that by SBI TSC can have the information to provide the mapping between transport slice and the underlying resources. Is considered SBI as internal interface in the TSC, for which in this case also the role of NEtwork controller would be mandated? I would clarify better this point that is very important to understand also the possibility for TSC to provide the mapping function described.

**Comment by Eric-Gray-Ericsson** [comment]
I added the paragraph about SBI because of discussion we had during one of the conference calls.  It was (at that time) generally agreed that the functional block "SBI" is added in order to provide a background concept for illustrating the role of the TSC in mapping transport slice requests received by the TSC to on e or more lower-layer network(s).  The concept is - as stated during the meeting - needed in order to avoid having to say stuff like "the TSC maps incoming slice requests to whatever it is that the TSC uses to configure lower layer network connectivity, resource allocation, etc.

This should be clearly stated as a logical construction as there is no intent in either the definition drafts nor this draft to define any specific SBI.

However, this should be fixed in the definitions draft, rather than here - so this paragraph will be removed and a related comment made toward the definitions draft.

**Comment by Eric-Gray-Ericsson** [comment]
As a result (based on the most recent comment exchange with Sergio, the current modified text for adding is:

Transport Slice Controller (TSC)

The transport slice controller takes abstract requests for
transport slices and implements them using a suitable underlying
technology. A transport slice controller is the key building
block for control and management of the transport slice. It
provides the creation/modification/deletion, monitoring and
optimization of transport Slices in a multi-domain, a
multi-technology and multi-vendor environment.

A TSC northbound interface (NBI) is needed for communicating
details of a transport slice, as well as providing information
to a slice requester/consumer about transport slice status
and performance. The details for this NBI are not in scope
for this document.

The controller provides the following functions:

* Provides a technology-agnostic NBI for creation/modification/
deletion of the transport slices. The API exposed by this NBI
communicates the endpoints of the transport slice, transport
slice SLO parameters (and possibly monitoring thresholds),
applicable input selection (filtering) and various policies, and
provides a way to monitor the slice.

* Determines an abstract topology connecting the endpoints of
the transport slice that meets criteria specified via the NBI.The
TSC also retains information about the mapping of this abstract
topology to underlying components of the transport slice as
necessary to monitor transport slice status and performance.

* Provides "Mapping Functions" for the realization of transport slices.
In other words, it will use the mapping functions which:

- map technology-agnostic NBI request to technology-specific SBIs.
- map filtering/selection information as necessary to entities in the
underlay network.

* Via an SBI, the controller collects Telemetry data (e.g. OAM results,
Statistics, States etc.) for all elements in the abstract topology used
to realize the transport slice.

* Using the Telemetry data from the underlying realization of a
transport slice (i.e. services/paths/tunnels), evaluates the
current performance against transport slice SLO parameters and
exposes them to the transport slice consumer via the NBI. The
TSC NBI may also include a capability to provide notification in
case the transport slice performance reaches threshold values
defined by the transport slice consumer.

**Comment by sergiobelotti** [comment]
> As a result (based on the most recent comment exchange with Sergio, the current modified text for adding is:
> 
> Transport Slice Controller (TSC)
> 
> The transport slice controller takes abstract requests for
> transport slices and implements them using a suitable underlying
> technology. A transport slice controller is the key building
> block for control and management of the transport slice. It
> provides the creation/modification/deletion, monitoring and
> optimization of transport Slices in a multi-domain, a
> multi-technology and multi-vendor environment.
> 
> A TSC northbound interface (NBI) is needed for communicating
> details of a transport slice, as well as providing information
> to a slice requester/consumer about transport slice status
> and performance. The details for this NBI are not in scope
> for this document.
> 
> The controller provides the following functions:
> 
> * Provides a technology-agnostic NBI for creation/modification/
>   deletion of the transport slices. The API exposed by this NBI
>   communicates the endpoints of the transport slice, transport
>   slice SLO parameters (and possibly monitoring thresholds),
>   applicable input selection (filtering) and various policies, and
>   provides a way to monitor the slice.
> * Determines an abstract topology connecting the endpoints of
>   the transport slice that meets criteria specified via the NBI.The
>   TSC also retains information about the mapping of this abstract
>   topology to underlying components of the transport slice as
>   necessary to monitor transport slice status and performance.
> * Provides "Mapping Functions" for the realization of transport slices.
>   In other words, it will use the mapping functions which:
> 
> * map technology-agnostic NBI request to technology-specific SBIs.
> * map filtering/selection information as necessary to entities in the
>   underlay network.
> 
> * Via an SBI, the controller collects Telemetry data (e.g. OAM results,
>   Statistics, States etc.) for all elements in the abstract topology used
>   to realize the transport slice.
> * Using the Telemetry data from the underlying realization of a
>   transport slice (i.e. services/paths/tunnels), evaluates the
>   current performance against transport slice SLO parameters and
>   exposes them to the transport slice consumer via the NBI. The
>   TSC NBI may also include a capability to provide notification in
>   case the transport slice performance reaches threshold values
>   defined by the transport slice consumer.

Thanks Eric, I'm fine with the text

**Pull request closed without merging**
